import type { Metadata } from "next";
import "./globals.scss";
import RootLayoutClient from "./layout.client";

import {
  Frank_Ruhl_Libre,
  Inter,
  Abril_Fatface,
  Lexend_Deca,
  Roboto,
  Montserrat,
  Poppins,
} from "next/font/google";

const frankRuhlLibre = Frank_Ruhl_Libre({
  subsets: ["latin"],
  weight: ["400", "700"],
});
const inter = Inter({ subsets: ["latin"], weight: ["400", "500", "700"] });
const abrilFatface = Abril_Fatface({ subsets: ["latin"], weight: ["400"] });
const lexendDeca = Lexend_Deca({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const geistMontserrat = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});
const geistPoppins = Poppins({
  variable: "--font-poppins-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${frankRuhlLibre.className} ${inter.className} 
        ${lexendDeca.className} ${roboto.className} ${abrilFatface.className} ${geistMontserrat.style} ${geistPoppins.style}`}
      >
        <RootLayoutClient>{children}</RootLayoutClient>
      </body>
    </html>
  );
}
